#!/usr/bin/env python3
"""secrets CLI — agent-native CLI for the 'secrets' resource pack.

Generated by agentic-anything. Zero dependencies (Python 3.10+ stdlib).
The pack directory defaults to the parent of this script's directory.

Commands (all support --json):
  info                     pack summary
  pages                    list captured pages
  page <page_id>           print one page (markdown by default, --format json)
  search <query...>        keyword search across pages with evidence
  apis                     list discovered endpoints/forms/feeds/specs
  forms                    list forms with fields
  fetch <url_or_path>      live GET against the site (same-origin only)
  form-curl <form_index>   print a ready-to-edit curl command for a form

Exit codes: 0 success, 1 error (message on stderr).
"""

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path
from urllib.parse import urljoin, urlsplit

PACK_DIR = Path(__file__).resolve().parent.parent
SITE_ID = 'secrets'
SEED_URL = 'https://docs.python.org/3.13/library/python-3.13-secrets.html'
USER_AGENT = "agentic-anything-sitecli/0.5.0"


def _read_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _fail(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _emit(data, as_json, human):
    if as_json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
    else:
        print(human)


def _site():
    return _read_json(PACK_DIR / "site.json")


def cmd_info(args):
    site = _site()
    data = {
        "site_id": site.get("site_id"),
        "seed_url": site.get("seed_url"),
        "captured_at": site.get("captured_at"),
        "capture_mode": site.get("capture_mode"),
        "page_count": site.get("page_count"),
        "frontier_count": len(site.get("frontier", [])),
    }
    human = "\n".join(f"{k}: {v}" for k, v in data.items())
    _emit(data, args.json, human)


def cmd_pages(args):
    pages = _site().get("pages", [])
    data = [
        {"page_id": p["page_id"], "type": p.get("page_type"), "title": p.get("title"),
          "url": p.get("url")} for p in pages
    ]
    human = "\n".join(f"{p['page_id']:<40} [{p['type']}] {p['title']}" for p in data)
    _emit(data, args.json, human or "(no pages)")


def cmd_page(args):
    if args.format == "json" or args.json:
        path = PACK_DIR / "pages" / f"{args.page_id}.json"
        if not path.exists():
            _fail(f"page '{args.page_id}' not found")
        print(path.read_text(encoding="utf-8"))
    else:
        path = PACK_DIR / "pages" / f"{args.page_id}.md"
        if not path.exists():
            _fail(f"page '{args.page_id}' not found")
        print(path.read_text(encoding="utf-8"))


_TOKEN_RE = re.compile(r"[^\W_]{2,}", re.UNICODE)


def _tokens(text):
    return set(_TOKEN_RE.findall((text or "").casefold()))


def _focused_snippet(text, query, limit=240):
    if len(text) <= limit:
        return text
    lowered = text.casefold()
    positions = []
    for token in query:
        start = 0
        while len(positions) < 200:
            found = lowered.find(token, start)
            if found < 0:
                break
            positions.append(found)
            start = found + max(1, len(token))
    if not positions:
        return text[:limit].rstrip() + "…"
    best = None
    for position in positions:
        start = max(0, min(len(text) - limit, position - limit // 3))
        window = text[start:start + limit]
        candidate = (len(query.intersection(_tokens(window))), -start, start)
        if best is None or candidate > best:
            best = candidate
    start = best[2]
    snippet = text[start:start + limit].strip()
    if start:
        snippet = "…" + snippet
    if start + limit < len(text):
        snippet += "…"
    return snippet


def cmd_search(args):
    query = _tokens(" ".join(args.query))
    if not query:
        _fail("empty query")
    results = []
    for p in _site().get("pages", []):
        manifest = _read_json(PACK_DIR / "pages" / f"{p['page_id']}.json")
        token_weights = {}
        evidence_candidates = []
        block_coverage = 0
        fields = [("title", manifest.get("title", ""), 5),
                  ("locator", manifest.get("locator", ""), 3)]
        fields += [("content", c.get("text", ""), 3 if c.get("kind") == "heading" else 1)
                   for c in manifest.get("content", [])]
        for order, (kind, text, weight) in enumerate(fields):
            hits = query.intersection(_tokens(text))
            if hits:
                block_coverage = max(block_coverage, len(hits))
                for token in hits:
                    token_weights[token] = max(weight, token_weights.get(token, 0))
                snippet = _focused_snippet(text, query)
                visible = query.intersection(_tokens(snippet))
                evidence_candidates.append((
                    -len(visible), -weight, order,
                    {"kind": kind, "text": snippet, "matched": sorted(visible)},
                ))
        if token_weights:
            evidence_candidates.sort(key=lambda item: (item[0], item[1], item[2]))
            results.append({
                "page_id": p["page_id"],
                "score": sum(token_weights.values()),
                "coverage": len(token_weights),
                "block_coverage": block_coverage,
                "title": manifest.get("title", ""),
                "evidence": [item[3] for item in evidence_candidates[:4]],
            })
    results.sort(key=lambda r: (
        -r["block_coverage"], -r["coverage"], -r["score"], r["page_id"]
    ))
    results = results[: args.top]
    human_lines = []
    for r in results:
        human_lines.append(f"{r['score']:>4}  {r['page_id']}  {r['title']}")
        for ev in r["evidence"]:
            human_lines.append(f"      - {ev['text'][:220]}")
    _emit(results, args.json, "\n".join(human_lines) or "(no matches)")


def cmd_apis(args):
    apis = _read_json(PACK_DIR / "api" / "apis.json")
    if args.json:
        print(json.dumps(apis, ensure_ascii=False, indent=2))
        return
    for key in ("endpoints", "observed_network", "openapi", "feeds", "well_known", "sitemaps"):
        for item in apis.get(key, []):
            label = item.get("url", "")
            method = item.get("method", "")
            print(f"[{key}] {method} {label}".strip())
    if not any(apis.get(k) for k in ("endpoints", "observed_network", "openapi", "feeds")):
        print("(no API endpoints discovered; see forms with the 'forms' command)")


def cmd_forms(args):
    forms = _read_json(PACK_DIR / "api" / "apis.json").get("forms", [])
    if args.json:
        print(json.dumps(forms, ensure_ascii=False, indent=2))
        return
    for idx, form in enumerate(forms):
        print(f"[{idx}] {form['method']} {form['action_url']} (page {form['page_id']})")
        for f in form.get("fields", []):
            req = " required" if f.get("required") else ""
            print(f"      {f['name']}: {f['type']}{req}")
    if not forms:
        print("(no forms found)")


def cmd_fetch(args):
    url = urljoin(SEED_URL, args.url)
    seed_host = urlsplit(SEED_URL).netloc
    if urlsplit(url).netloc != seed_host:
        _fail(f"fetch is limited to {seed_host} (same-origin safety)")
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read(2_000_000)
            ctype = resp.headers.get("Content-Type", "")
    except Exception as exc:
        _fail(f"fetch failed: {exc}")
    if args.json:
        try:
            parsed = json.loads(body)
            print(json.dumps({"url": url, "content_type": ctype, "body": parsed},
                             ensure_ascii=False, indent=2))
            return
        except ValueError:
            print(json.dumps({"url": url, "content_type": ctype,
                               "body": body.decode("utf-8", "replace")[:100000]},
                             ensure_ascii=False, indent=2))
            return
    sys.stdout.write(body.decode("utf-8", "replace"))


def cmd_form_curl(args):
    forms = _read_json(PACK_DIR / "api" / "apis.json").get("forms", [])
    if not (0 <= args.form_index < len(forms)):
        _fail(f"form index out of range (0..{len(forms) - 1})")
    form = forms[args.form_index]
    method = form["method"].upper()
    if method in ("GET", "HEAD"):
        # GET forms submit as query parameters: curl -G + --data-urlencode
        parts = [f"curl -G '{form['action_url']}'"]
        flag = "--data-urlencode"
    else:
        parts = [f"curl -X {method} '{form['action_url']}'"]
        flag = "-d"
    for f in form.get("fields", []):
        placeholder = f"<{f['type']}>"
        parts.append(f"  {flag} '{f['name']}={placeholder}'")
    cmd = " \\\n".join(parts)
    _emit({"curl": cmd, "form": form}, args.json, cmd)


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    # --json is accepted anywhere (before or after the subcommand).
    json_flag = "--json" in argv
    argv = [a for a in argv if a != "--json"]

    parser = argparse.ArgumentParser(prog=f"{SITE_ID}-cli", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--json", action="store_true",
                        help="machine-readable output (accepted anywhere)")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("info").set_defaults(func=cmd_info)
    sub.add_parser("pages").set_defaults(func=cmd_pages)

    p = sub.add_parser("page")
    p.add_argument("page_id")
    p.add_argument("--format", choices=["md", "json"], default="md")
    p.set_defaults(func=cmd_page)

    p = sub.add_parser("search")
    p.add_argument("query", nargs="+")
    p.add_argument("--top", type=int, default=5)
    p.set_defaults(func=cmd_search)

    sub.add_parser("apis").set_defaults(func=cmd_apis)
    sub.add_parser("forms").set_defaults(func=cmd_forms)

    p = sub.add_parser("fetch")
    p.add_argument("url", help="absolute URL or path on the site")
    p.set_defaults(func=cmd_fetch)

    p = sub.add_parser("form-curl")
    p.add_argument("form_index", type=int)
    p.set_defaults(func=cmd_form_curl)

    args = parser.parse_args(argv)
    args.json = json_flag
    try:
        args.func(args)
    except FileNotFoundError as exc:
        _fail(f"pack file missing: {exc} — is this script inside a complete resource pack?")
    except json.JSONDecodeError as exc:
        _fail(f"corrupt pack file: {exc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
